import Footer from '@/layout/footer/Footer';
import Header from '@/layout/header/Header';
import type { Metadata } from 'next';
import { Montserrat, Roboto_Mono } from 'next/font/google';
import './globals.css';
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--font-montserrat',
	display: 'swap',
});

const roboto_mono = Roboto_Mono({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto-mono',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable} ${roboto_mono.variable}`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
